# Generated by Django 3.1.7 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Configuration', '0002_auto_20230925_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='EformFieldData',
            fields=[
                ('eform_field_data_guid', models.CharField(db_column='EFORM_FIELD_DATA_GUID', max_length=40, primary_key=True, serialize=False)),
                ('cart_guid', models.CharField(db_column='CART_GUID', max_length=32, null=True)),
                ('favourite_cart_guid', models.CharField(db_column='FAVOURITE_CART_GUID', max_length=32, null=True)),
                ('eform_id', models.CharField(db_column='EFORM_ID', max_length=40, null=True)),
                ('eform_type', models.CharField(db_column='EFORM_TYPE', max_length=40)),
                ('eform_field_name', models.CharField(db_column='EFORM_FIELD_NAME', max_length=200, null=True)),
                ('eform_field_data', models.CharField(db_column='EFORM_FIELD_DATA', max_length=1000, null=True)),
                ('eform_field_count', models.PositiveIntegerField(db_column='EFORM_FIELD_COUNT', null=True)),
                ('eform_field_data_created_at', models.DateTimeField(db_column='EFORM_FIELD_DATA_CREATED_AT', null=True)),
                ('eform_field_data_created_by', models.CharField(db_column='EFORM_FIELD_DATA_CREATED_BY', max_length=12, null=True)),
                ('eform_field_data_changed_at', models.DateTimeField(blank=True, db_column='EFORM_FIELD_DATA_CHANGED_AT', null=True)),
                ('eform_field_data_changed_by', models.CharField(db_column='EFORM_FIELD_DATA_CHANGED_BY', max_length=12, null=True)),
                ('eform_field_data_source_system', models.CharField(db_column='EFORM_FIELD_DATA_SOURCE_SYSTEM', max_length=20)),
                ('eform_field_data_destination_system', models.CharField(db_column='EFORM_FIELD_DATA_DESTINATION_SYSTEM', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MTD_EFORM_FIELD_DATA',
                'managed': True,
            },
        ),
    ]
