# Generated by Django 3.1.7 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Shopping_Cart', '0001_initial'),
        ('eProc_Purchase_Order', '0001_initial'),
        ('eProc_Form_Builder', '0001_initial'),
        ('eProc_Configuration', '0002_auto_20230925_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='eformfielddata',
            name='item_guid',
            field=models.ForeignKey(db_column='ITEM_GUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Shopping_Cart.scitem'),
        ),
        migrations.AddField(
            model_name='eformfielddata',
            name='po_item_guid',
            field=models.ForeignKey(blank=True, db_column='PO_ITEM_GUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Purchase_Order.poitem'),
        ),
        migrations.AddField(
            model_name='eformfielddata',
            name='product_eform_pricing_guid',
            field=models.ForeignKey(db_column='product_eform_pricing_guid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.producteformpricing'),
        ),
    ]
