# Generated by Django 3.1.7 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgModel',
            fields=[
                ('object_id', models.PositiveBigIntegerField(db_column='OBJECT_ID', primary_key=True, serialize=False)),
                ('node_guid', models.CharField(db_column='NODE_GUID', max_length=32, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=60)),
                ('parent_node_guid', models.CharField(db_column='PARENT_NODE_GUID', max_length=32, null=True)),
                ('node_type', models.CharField(db_column='NODE_TYPE', max_length=10)),
                ('root_node_object_id', models.PositiveIntegerField(db_column='ROOT_NODE_OBJECT_ID', null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('org_model_created_at', models.DateTimeField(blank=True, db_column='ORG_MODEL_CREATED_AT', null=True)),
                ('org_model_created_by', models.CharField(db_column='ORG_MODEL_CREATED_BY', max_length=30, null=True)),
                ('org_model_changed_at', models.DateTimeField(blank=True, db_column='ORG_MODEL_CHANGED_AT', null=True)),
                ('org_model_changed_by', models.CharField(db_column='ORG_MODEL_CHANGED_BY', max_length=30, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MTD_ORG_MODEL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgNames',
            fields=[
                ('root_node', models.CharField(db_column='ROOT_NODE', max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=60)),
                ('org_names_created_by', models.CharField(db_column='ORG_NAMES_CREATED_BY', max_length=30, null=True)),
                ('org_names_created_at', models.DateTimeField(db_column='ORG_NAMES_CREATED_AT', max_length=50, null=True)),
                ('org_names_changed_by', models.CharField(db_column='ORG_NAMES_CHANGED_BY', max_length=30, null=True)),
                ('org_names_changed_at', models.DateTimeField(db_column='ORG_NAMES_CHANGED_AT', max_length=50, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
                ('object_id', models.ForeignKey(db_column='OBJECT_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Org_Model.orgmodel')),
            ],
            options={
                'db_table': 'MTD_ORG_NAMES',
                'managed': True,
                'unique_together': {('client', 'name')},
            },
        ),
    ]
