from django.urls import path
from . import views

app_name = 'eProc_Application_Settings'

urlpatterns = [
    path('extract_node_type_data/', views.extract_node_type_data, name='extract_node_type_data'),
    path('extract_attributes_data/', views.extract_attributes_data, name='extract_attributes_data'),
    path('extract_node_level_attributes_data/', views.extract_node_level_attributes_data,
         name='extract_node_level_attributes_data'),
    path('extract_user_role_data/', views.extract_user_role_data, name='extract_user_role_data'),
    path('extract_account_assignment_category_data/', views.extract_account_assignment_category_data,
         name='extract_account_assignment_category_data'),
    path('extract_favourite_cart_number_range_data/', views.extract_favourite_cart_number_range_data,
         name='extract_favourite_cart_number_range_data'),
    path('extract_shopping_cart_number_range_data/', views.extract_shopping_cart_number_range_data,
         name='extract_shopping_cart_number_range_data'),
    path('extract_purchase_order_number_range_data/', views.extract_purchase_order_number_range_data,
         name='extract_purchase_order_number_range_data'),
    path('extract_goods_verification_number_range_data/', views.extract_goods_verification_number_range_data,
         name='extract_goods_verification_number_range_data'),
    path('extract_favourite_transaction_type_data/', views.extract_favourite_transaction_type_data,
         name='extract_favourite_transaction_type_data'),
    path('extract_shopping_cart_transaction_type_data/', views.extract_shopping_cart_transaction_type_data,
         name='extract_shopping_cart_transaction_type_data'),
    path('extract_purchase_order_transaction_type_data/', views.extract_purchase_order_transaction_type_data,
         name='extract_purchase_order_transaction_type_data'),
    path('extract_goods_verification_transaction_type_data/', views.extract_goods_verification_transaction_type_data,
         name='extract_goods_verification_transaction_type_data'),
    path('extract_po_split_type_data/', views.extract_po_split_type_data, name='extract_po_split_type_data'),
    path('extract_po_split_criteria_data/', views.extract_po_split_criteria_data,
         name='extract_po_split_criteria_data'),
    path('extract_purchase_control_data/', views.extract_purchase_control_data,
         name='extract_purchase_control_data'),
    path('extract_source_rule_data/', views.extract_source_rule_data,
         name='extract_source_rule_data'),
    path('extract_source_mapping_data/', views.extract_source_mapping_data,
         name='extract_source_mapping_data'),
    path('extract_authorization_object_data/', views.extract_authorization_object_data,
         name='extract_authorization_object_data'),
    path('extract_attributes_group_data/', views.extract_attributes_group_data, name='extract_attributes_group_data'),
    path('extract_authorization_data', views.extract_authorization_data, name='extract_authorization_data'),
    path('extract_message_id_data', views.extract_message_id_data, name='extract_message_id_data'),
    path('extract_message_id_desc_data', views.extract_message_id_desc_data, name='extract_message_id_desc_data'),
    path('get_number_ranges/', views.get_number_ranges, name='get_number_ranges'),
    path('clients/', views.upload_clients, name='upload_clients'),
    path('UNSPSC_codes/', views.upload_product_category, name='upload_product_category'),
    path('org_node_types', views.org_node_types, name='org_node_types'),
    path('document_types/', views.upload_document_type, name='upload_document_type'),
    path('sc_number_ranges/', views.number_range_shopping_cart, name='number_range_shopping_cart'),
    path('po_number_ranges/', views.number_range_purchase_order, name='number_range_purchase_order'),
    path('confirmation_number_ranges/', views.number_range_goods_verification, name='number_range_goods_verification'),
    path('fav_number_ranges/', views.number_range_favourite_cart, name='number_range_favourite_cart'),
    path('roles', views.roles, name='roles'),
    path('authorization_objects', views.auth_objects, name='auth_objects'),
    path('authorization_grp', views.auth_grp, name='auth_grp'),
    path('org_attributes', views.org_attributes, name='org_attributes'),
    path('org_node_level_attributes', views.org_attributes_level, name='org_attributes_level'),
    path('authorization', views.auth, name='auth'),
    path('favourite_transaction_types/', views.transaction_type, name='transaction_type'),
    path('sc_transaction_types/', views.transaction_type_sc, name='transaction_type_sc'),
    path('po_transaction_types/', views.transaction_type_po, name='transaction_type_po'),
    path('gv_transaction_types/', views.transaction_type_gv, name='transaction_type_gv'),
    path('ACC/', views.upload_acc_assign_categories, name='upload_acc_assign_categories'),
    path('po_split_criteria/', views.upload_po_split_criteria, name='upload_po_split_criteria'),
    path('po_split_type/', views.upload_po_split_type, name='upload_po_split_type'),
    path('calendars', views.display_calendar, name='display_calendar'),
    path('holidays', views.display_holidays, name='display_holidays'),
    path('message_numbers/', views.display_messages_id, name='display_messages_id'),
    path('message_descriptions/', views.display_messages_desc, name='display_messages_desc'),
    path('edit_create_number_ranges/', views.edit_create_number_ranges, name='edit_create_number_ranges'),
    path('get_transaction_type/', views.get_transaction_type, name='get_transaction_type'),
    path('edit_create_transaction_types/', views.edit_create_transaction_types, name='edit_create_transaction_types'),
    path('purch_cockpit', views.purch_cockpit_display, name='purch_cockpit'),
    path('save_purch_cockpit', views.save_purch_cockpit_data, name='save_purch_cockpit'),
    path('save_product_details_images', views.save_product_details_images, name='save_product_details_images'),
    path('display_purchase_control', views.display_purchase_control, name='display_purchase_control'),
    path('display_sourcing_rule_generic', views.display_sourcing_rule_generic, name='display_sourcing_rule_generic'),
    path('display_sourcing_mapping_specific', views.display_sourcing_mapping_specific,
         name='display_sourcing_mapping_specific'),
]
