# Generated by Django 3.1.7 on 2023-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpGenerator',
            fields=[
                ('email', models.EmailField(db_column='EMAIL', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='PASSWORD', max_length=256, null=True)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=30)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=30)),
                ('otp', models.CharField(db_column='OTP', max_length=4, null=True)),
                ('otp_locked', models.BooleanField(db_column='OTP_LOCKED', default=False)),
                ('otp_attempts', models.PositiveIntegerField(db_column='OTP_ATTEMPTS', default=False)),
                ('otp_generator_created_by', models.CharField(db_column='OTP_GENERATOR_CREATED_BY', max_length=30, null=True)),
                ('otp_generator_created_at', models.DateTimeField(db_column='OTP_GENERATOR_CREATED_AT', max_length=50, null=True)),
                ('otp_generator_changed_by', models.CharField(db_column='OTP_GENERATOR_CHANGED_BY', max_length=30, null=True)),
                ('otp_generator_changed_at', models.DateTimeField(db_column='OTP_GENERATOR_CHANGED_AT', max_length=50, null=True)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'MTD_OTP_GENERATOR',
                'managed': True,
            },
        ),
    ]
