# Generated by Django 3.1.7 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Attributes', '0001_initial'),
        ('eProc_Org_Model', '0001_initial'),
        ('eProc_Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgattributeslevel',
            name='attribute_id',
            field=models.ForeignKey(db_column='ATTRIBUTE_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgattributes', verbose_name='attribute_id'),
        ),
        migrations.AddField(
            model_name='orgattributeslevel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgattributeslevel',
            name='object_id',
            field=models.ForeignKey(db_column='OBJECT_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Org_Model.orgmodel'),
        ),
    ]
