# Generated by Django 3.1.7 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Org_Model', '0001_initial'),
        ('eProc_Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgporgmapping',
            name='object_id',
            field=models.ForeignKey(db_column='OBJECT_ID', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Org_Model.orgmodel'),
        ),
        migrations.AddField(
            model_name='orgporg',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgporg',
            name='object_id',
            field=models.ForeignKey(db_column='OBJECT_ID', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Org_Model.orgmodel'),
        ),
        migrations.AddField(
            model_name='orgpgroup',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgpgroup',
            name='object_id',
            field=models.ForeignKey(db_column='OBJECT_ID', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Org_Model.orgmodel'),
        ),
        migrations.AddField(
            model_name='orgnodetypes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgmodelnodetypeconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgcompanies',
            name='client',
            field=models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgcompanies',
            name='object_id',
            field=models.ForeignKey(db_column='OBJECT_ID', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Org_Model.orgmodel'),
        ),
        migrations.AddField(
            model_name='orgattributesdesc',
            name='attribute_id',
            field=models.ForeignKey(db_column='ATTRIBUTE_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgattributes', verbose_name='attribute_id'),
        ),
        migrations.AddField(
            model_name='orgattributesdesc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgattributesdesc',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='orgaddressmap',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='address_partner_type',
            field=models.ForeignKey(db_column='ADDRESS_PARTNER_TYPE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.addresspartnertype'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='country_code',
            field=models.ForeignKey(db_column='COUNTRY_CODE', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.country', verbose_name='country_code'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='time_zone',
            field=models.ForeignKey(db_column='TIME_ZONE', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.timezone'),
        ),
        migrations.AddField(
            model_name='numberranges',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='numberranges',
            name='document_type',
            field=models.ForeignKey(db_column='DOCUMENT_TYPE', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.documenttype'),
        ),
        migrations.AddField(
            model_name='notifsettingsdesc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='notifsettingsdesc',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='notifsettings',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='notifkeywordsdesc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='notifkeywordsdesc',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='notifkeywords',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='notificationtypedesc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='notificationtypedesc',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='messagesiddesc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='messagesiddesc',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', max_length=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='messagesid',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='imagesupload',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='freetextform',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='freetextdetails',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='freetextdetails',
            name='currency_id',
            field=models.ForeignKey(db_column='CURRENCY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.currency'),
        ),
        migrations.AddField(
            model_name='fieldtypedescription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='fieldtypedescription',
            name='field_name',
            field=models.ForeignKey(db_column='FIELD_NAME', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.fielddesc'),
        ),
        migrations.AddField(
            model_name='fieldtypedesc',
            name='field_name',
            field=models.ForeignKey(db_column='FIELD_NAME', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.fielddesc'),
        ),
        migrations.AddField(
            model_name='emailobjecttypes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='emailkeywords',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='emailcontents',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='emailcontents',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='eformfieldconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='documenttypecust',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='documenttypecust',
            name='document_type',
            field=models.ForeignKey(db_column='DOCUMENT_TYPE', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.documenttype'),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='document_type',
            field=models.ForeignKey(db_column='DOCUMENT_TYPE', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.documenttype'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='determineglaccount',
            name='account_assign_cat',
            field=models.ForeignKey(db_column='ACCOUNT_ASSIGN_CAT', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.accountassignmentcategory'),
        ),
        migrations.AddField(
            model_name='determineglaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='determineglaccount',
            name='currency_id',
            field=models.ForeignKey(db_column='CURRENCY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.currency'),
        ),
        migrations.AddField(
            model_name='countrycompcode',
            name='client',
            field=models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='countrycompcode',
            name='country',
            field=models.ForeignKey(db_column='COUNTRY', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.country'),
        ),
        migrations.AddField(
            model_name='companygrpuser',
            name='client',
            field=models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='companycodegrp',
            name='client',
            field=models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='catalogmapping',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='calenderholidays',
            name='client',
            field=models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='calenderconfig',
            name='client',
            field=models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='calenderconfig',
            name='country_code',
            field=models.ForeignKey(db_column='COUNTRY_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.country', verbose_name='country_code'),
        ),
        migrations.AddField(
            model_name='authorizationgroup',
            name='auth_obj_id',
            field=models.ForeignKey(db_column='AUTH_OBJ_ID', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.authorizationobject'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='role',
            field=models.ForeignKey(db_column='ROLE', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.userroles'),
        ),
        migrations.AddField(
            model_name='approverlimitvalue',
            name='app_types',
            field=models.ForeignKey(db_column='APP_TYPES', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.approvertype'),
        ),
        migrations.AddField(
            model_name='approverlimitvalue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='approverlimitvalue',
            name='currency_id',
            field=models.ForeignKey(db_column='CURRENCY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.currency'),
        ),
        migrations.AddField(
            model_name='approverlimit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='accountingdatadesc',
            name='account_assign_cat',
            field=models.ForeignKey(db_column='ACCOUNT_ASSIGN_CAT', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.accountassignmentcategory'),
        ),
        migrations.AddField(
            model_name='accountingdatadesc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='accountingdatadesc',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='accountingdata',
            name='account_assign_cat',
            field=models.ForeignKey(db_column='ACCOUNT_ASSIGN_CAT', on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.accountassignmentcategory'),
        ),
        migrations.AddField(
            model_name='accountingdata',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='accountassignmentcategorycust',
            name='account_assign_cat',
            field=models.ForeignKey(db_column='ACCOUNT_ASSIGN_CAT', null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.accountassignmentcategory'),
        ),
        migrations.AddField(
            model_name='accountassignmentcategorycust',
            name='client',
            field=models.ForeignKey(db_column='CLIENT', null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AlterUniqueTogether(
            name='variantconfig',
            unique_together={('client', 'variant_id', 'variant_count')},
        ),
        migrations.AlterUniqueTogether(
            name='userrolescust',
            unique_together={('client', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='unspsccategoriescustdesc',
            unique_together={('client', 'language_id', 'prod_cat_id', 'unspsc_categories_cust_desc_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='unspsccategoriescust',
            unique_together={('client', 'prod_cat_id', 'unspsc_categories_cust_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypes',
            unique_together={('client', 'transaction_type', 'document_type', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='systemsettingsconfig',
            unique_together={('sys_attr_type', 'sys_attr_value', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliermaster',
            unique_together={('client', 'email', 'company_id', 'supplier_master_source_system'), ('client', 'supplier_id', 'company_id', 'supplier_master_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='spendlimitvalue',
            unique_together={('spend_code_id', 'client', 'company_id', 'spend_limit_value_source_system', 'currency_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sapconnector',
            unique_together={('ashost', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='projectscategories',
            unique_together={('client', 'project_category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projectdetails',
            unique_together={('client', 'project_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projectcategoriesmapping',
            unique_together={('client', 'project_category_id', 'project_id')},
        ),
        migrations.AlterUniqueTogether(
            name='productsdetail',
            unique_together={('client', 'product_id', 'products_detail_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='payterms',
            unique_together={('client', 'payment_term_key')},
        ),
        migrations.AlterUniqueTogether(
            name='orgporg',
            unique_together={('client', 'porg_id', 'company_id', 'org_porg_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='orgpgroup',
            unique_together={('client', 'pgroup_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgnodetypes',
            unique_together={('client', 'node_type')},
        ),
        migrations.AlterUniqueTogether(
            name='orgmodelnodetypeconfig',
            unique_together={('client', 'org_model_types', 'node_values', 'node_type')},
        ),
        migrations.AlterUniqueTogether(
            name='orgcompanies',
            unique_together={('client', 'company_id', 'org_companies_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='orgattributesdesc',
            unique_together={('client', 'attribute_id', 'language_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgaddressmap',
            unique_together={('client', 'address_type', 'address_number', 'org_address_map_source_system', 'company_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgaddress',
            unique_together={('client', 'address_number', 'org_address_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='numberranges',
            unique_together={('client', 'document_type', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='notifsettingsdesc',
            unique_together={('variant_name', 'language_id', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='notifsettings',
            unique_together={('variant_name', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='notifkeywords',
            unique_together={('variant_name', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationtypedesc',
            unique_together={('notification_type_id', 'client', 'language_id')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationtype',
            unique_together={('notification_type_id', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='freetextform',
            unique_together={('client', 'supp_id', 'prod_cat_id', 'catalog_id')},
        ),
        migrations.AlterUniqueTogether(
            name='freetextdetails',
            unique_together={('client', 'freetext_id', 'supplier_id', 'prod_cat_id')},
        ),
        migrations.AlterUniqueTogether(
            name='emailobjecttypes',
            unique_together={('object_type', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='emailcontents',
            unique_together={('object_type', 'language_id', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='eformfieldconfig',
            unique_together={('client', 'eform_id', 'eform_field_count')},
        ),
        migrations.AlterUniqueTogether(
            name='documenttypecust',
            unique_together={('client', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='countrycompcode',
            unique_together={('client', 'company_code_id')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogs',
            unique_together={('client', 'catalog_id')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogmapping',
            unique_together={('client', 'item_id', 'catalog_id', 'catalogs_mapping_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='calenderconfig',
            unique_together={('client', 'calender_id', 'year', 'country_code')},
        ),
        migrations.AlterUniqueTogether(
            name='authorization',
            unique_together={('client', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='approverlimitvalue',
            unique_together={('client', 'app_code_id', 'app_types', 'company_id', 'approver_limit_value_source_system', 'currency_id')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingdatadesc',
            unique_together={('client', 'account_assign_value', 'account_assign_cat', 'company_id', 'language_id', 'accounting_data_desc_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingdata',
            unique_together={('client', 'account_assign_value', 'account_assign_cat', 'company_id', 'accounting_data_source_system')},
        ),
        migrations.AlterUniqueTogether(
            name='accountassignmentcategorycust',
            unique_together={('client', 'acc_cat_cust_source_system', 'acc_cat_cust')},
        ),
    ]
