# attribute id
CONST_ACC_CAT = 'ACC_CAT'
CONST_CT_CTR = 'CT_CTR'
CONST_WBS_ELEM = 'WBS_ELEM'
CONST_INT_ORD = 'INT_ORD'
CONST_AS_SET = 'AS_SET'
CONST_DEF_DOC_SEARCH = 'DEF_DOC_SEARCH'
CONST_DEL_ADDR = 'DEL_ADDR'
CONST_INV_ADDR = 'INV_ADDR'
CONST_US_ROLE = 'US_ROLE'
CONST_CO_CODE = 'CO_CODE'
CONST_ACS_VEND = 'ACS_VEND'
CONST_CAT_ID = 'CAT_ID'
CONST_GEN_ACC = 'GEN_ACC'
CONST_L_CURR = 'L_CURR'
CONST_BUY_ONB = 'BUY_ONB'
CONST_APPR_LIMI = 'APPR_LIMI'
CONST_ATT_ALW = 'ATT_ALW'
CONST_LEG_NAME = 'LEG_NAME'
CONST_PROD_CAT = 'PROD_CAT'
CONST_SPEND_LIMI = 'SPEND_LIMI'
CONST_US_SUBS = 'US_SUBS'
CONST_PURCH_ORG = 'PURCH_ORG'
CONST_PURCH_GRP = 'PURCH_GRP'
CONST_RESP_PROD_CAT = 'RESP_PROD_CAT'
CONST_FREE_TEXT_ID = 'FREE_TEXT'
CONST_SC_TRANS_TYPE = 'SC_TRANS_TYPE'
CONST_PO_TRANS_TYPE = 'PO_TRANS_TYPE'
CONST_FC_TRANS_TYPE = 'FC_TRANS_TYPE'
CONST_PROJECT_ID = 'PROJECT_ID'

# node type
CONST_RNODE = 'RNODE'
CONST_COMPANY_CODE = 'CCODE'
CONST_PORG = 'PORG'
CONST_PGROUP = 'PGRP'
CONST_NODE = 'NODE'
CONST_USER = 'USER'
CONST_PLANT = 'PLANT'
CONST_NODE_TYPES_LIST = ['RNODE', 'CCODE', 'PORG', 'PGRP', 'NODE', 'PLANT', 'USER']

CONST_IT01 = 'Materail'
CONST_IT02 = 'Service'
CONST_LIMI = 'Limit'

CONST_CATALOG_CALLOFF = '01'  # 'Catalog'
CONST_FREETEXT_CALLOFF = '02'  # 'Freetext'
CONST_PR_CALLOFF = '03'  # 'PR'
CONST_LIMIT_ORDER_CALLOFF = '04'  # 'Limit'

CONST_SF01 = 'SF'

# email_notification
CONST_USER_REG = 'REGISTRATION'

# Constants for keywords
CONST_CLIENT = '@client@'
CONST_CLIENT_NAME = '@client_name@'
CONST_PASSWORD = '@password@'
CONST_USER_NAME = '@username@'
CONST_FIRST_NAME = '@first_name@'
CONST_DOC_NUMBER = '@doc_number@'
CONST_CREATED_AT = '@created_at@'
CONST_APP_ID = '@app_id@'
CONST_PWD = 'Majjaka@123'
CONST_LOGIN_BUTTON = '@login_button@'
CONST_MAJJAKA_LOGO = '@majjaka_logo@'
CONST_COMP_CODE = '@company_code@'
CONST_ORDERED_BY = '@ordered_by@'
CONST_TOTAL_VAL = '@total_val@'
CONST_ITEM_DESC = '@item_desc@'
CONST_QUANTITY = '@qty@'
CONST_PRICE = '@price@'
CONST_COST_OBJECT = '@cost_object@'
CONST_ACCT_SPLIT_POS = '@acct_split_pos@'
CONST_DISTRIBUTION = '@distribution@'
CONST_ACCT_CATEGORY = '@acct_category@'
CONST_GL_ACCT = '@gl_acct@'
CONST_STEP_NO = '@step_no@'
CONST_APPROVER = '@approver@'
CONST_APPROVER_ID = '@approver_id@'
CONST_DECISION_STATUS = '@decision_status@'
CONST_APPROVAL_STATUS = '@approval_status@'
CONST_RECEIVED_ON = '@received_on@'
CONST_PROCESSED_ON = '@processed_on@'
CONST_CURRENCY = '@currency@'
CONST_REQUIRED_ON = '@required_on@'
CONST_UNIT = '@unit@'
CONST_SUPPLIER_ID = '@supplier_id@'
CONST_SUPPLIER_USERNAME = '@supplier_username@'
CONST_SUPPLIER_EMAIL = '@supplier_email@'
CONST_APP_DESC = '@app_desc@'
CONST_TIME_ZONE = '@time_zone@'
CONST_PRODUCT_ID = '@product_id@'
CONST_RESET_LINK = '@reset_link@'
CONST_SC_DESCRIPTION = '@sc_description@'

# Notes and Attachments
CONST_DOC_TYPE_SC = 'DOC01'
CONST_DOC_TYPE_PO = 'DOC02'
CONST_DOC_TYPE_CONF = 'DOC03'
CONST_DOC_TYPE_FC = 'DOC04'
CONST_ALL = '*'
# approver type
CONST_FIN = 'FIN'
CONST_CAT = 'CAT'
CONST_PURCH = 'PURCH'

# registration email

CONST_EMAIL = '@email@'

# Attributes header
CONST_TYPE = 'Type'
CONST_VALUE = 'Value'
CONST_DEFAULT = 'Default'
CONST_INHERIT = 'Inherit'
CONST_EXCLUDE = 'Exclude'
CONST_ACTION = 'Action'
CONST_IC = 'Invoice & Confirmation Only'
CONST_IO = 'Confirmation Only'

# Account assignment values
CONST_CC = 'CC'
CONST_OR = 'OR'
CONST_WBS = 'WBS'
CONST_AS = 'AS'
CONST_GLACC = 'GLACC'

# User Admin Page
CONST_USER_LIST = 'USER'
CONST_SUPPLIER_LIST = 'SUPPLIER'
CONST_DATE_FORMAT = ['DD.MM.YYYY', 'MM/DD/YYYY', 'MM-DD-YYYY', 'YYYY.MM.DD', 'YYYY/MM/DD', 'YYYY-MM-DD']
CONST_DECIMAL_NOTATION = ['1.234.567,89', '1,234,567.89', '1 234 567,89']

# User Role
CONST_SHOP = 'SHOP'
CONST_SHOP_PLUS = 'SHOP_PLUS'
CONST_SHOP_MANAGER = 'SHOP_MANAGER'
CONST_SHOP_ASSIST = 'SHOP_ASSIST'
CONST_SHOP_PURCHASER = 'SHOP_PURCHASER'
CONST_SHOP_ADMIN = 'SHOP_ADMIN'

CONST_DEFAULT_CLIENT = '999'

# auth level
CONST_FEATURE = 'Feature'
CONST_FORM = 'Form'
CONST_FIELD = 'Field'
# FEATURE
CONST_WORK_OVERVIEW = 'WORK_OVERVIEW'
CONST_USER_SETTINGS = 'USER_SETTINGS'
CONST_APPL_SETTINGS = 'APPL_SETTINGS'
CONST_MARKETING = 'MARKETING'
CONST_SHOPPING = 'SHOPPING'
CONST_SHOPPING_PLUS = 'SHOPPING_PLUS'
CONST_GOODS_RECEIPTS = 'GOODS_RECEIPTS'
CONST_APPROVALS = 'APPROVALS'
CONST_PURCHASING = 'PURCHASING'
CONST_SYSTEM_SETTINGS = 'SYSTEM_SETTINGS'
CONST_ADMIN_TOOL = 'ADMIN_TOOL'
CONST_CONTENT_MANAGEMENT = 'CONTENT_MANAGEMENT'
CONST_TIME_SHEET = 'TIME_SHEET'
CONST_SOM = 'SOM'
CONST_SHOPPER_ASSIST = 'SHOP_ASSIST'
CONST_SC_SOURCING = 'SC_SOURCING'

# auth level ID FORM
CONST_HOME = 'HOME'
CONST_LIMIT_ORDER = 'LIMIT_ORDER'
CONST_FREE_TEXT = 'FREE_TEXT'
CONST_REQUISITION = 'REQUISITION'
CONST_CATALOG = 'CATALOG'
CONST_MY_ORDER = 'MY_ORDER'
CONST_EMAIL_NOTIF = 'EMAIL_NOTIF'
CONST_REPORTS = 'REPORTS'
CONST_USER_ADMIN = 'USER_ADMIN'
CONST_SUBSTITUTION = 'SUBSTITUTION'
CONST_CONFIG_HOME = 'CONFIG_HOME'
CONST_SC_COMPLETION = 'SC_COMPLETION'
CONST_CHANGE_PO = 'CHANGE_PO'
CONST_PERSONAL_SETTINGS = 'PERSONAL_SETTINGS'
CONST_PURCHASE_SETTINGS = 'PURCHASE_SETTINGS'
CONST_FORM_BUILDER = 'FORM_BUILDER'
CONST_ORG_MODEL = 'ORG_MODEL'
CONST_CONFIRMATION = 'CONFIRMATION'
CONST_CANCELLATION = 'CANCELLATION'
CONST_RETURN_DELIVERY = 'RETURN_DELIVERY'
CONST_WORK_FLOW_ITEMS = 'WORK_FLOW_ITEMS'
CONST_SUPPLIER_MANAGEMENT = 'SUPPLIER_MANAGEMENT'
CONST_EMPLOYEE_MANAGEMENT = 'EMPLOYEE_MANAGEMENT'
CONST_SOBO = 'SOBO'
CONST_PRODUCT_AND_SERVICE_CONFIG = 'PRODUCT_AND_SERVICE_CONFIG'
CONST_CATALOG_CONFIG = 'CATALOG_CONFIG'
CONST_BASIC_SETTINGS = 'BASIC_SETTINGS'
CONST_APPLICATION_MONITOR = 'APPLICATION_MONITOR'
CONST_PROJECTS = 'PROJECTS'
CONST_EFFORTS = 'EFFORTS'
CONST_SUB_SOM = 'SUB_SOM'
CONST_GROUP_CATEGORY = 'SOURCING'
CONST_SC_GROUPING = 'SC_GROUPING'
CONST_RFQ = 'RFQ'
CONST_SEND_MESSAGE = 'SEND_MESSAGE'

#  FIELD ID
CONST_PASSWORD_POLICY = 'PASSWORD_POLICY'
CONST_LOGIN_ATTEMPTS = 'LOGIN_ATTEMPTS'
CONST_SESSION_TIMEOUT = 'SESSION_TIMEOUT'
CONST_DISPLAY_TIME = 'DISPLAY_TIME'
CONST_ATTACHMENT_SIZE = 'ATTACHMENT_SIZE'
CONST_ATTACHMENT_EXT = 'ATTACHMENT_EXT'
CONST_APPROVAL_LIMIT = 'APPROVAL_LIMIT'

# Process level status
CONST_ACTIVE = 'ACTIVE'
CONST_COMPLETED = 'COMPLETED'
CONST_INITIATED = 'INITIATED'

# Approver status
CONST_SC_APPR_OPEN = 'OPEN'
CONST_SC_APPR_APPROVED = 'APPROVER_APPROVED'
CONST_SC_APPR_REJECTED = 'APPROVER_REJECTED'
CONST_SC_APPR_INQUIRED = 'APPROVER_INQUIRED'

# type of approvals
CONST_AUTO = 'Auto'
CONST_MULTIPLE = 'Multiple'
CONST_FIN_APP = 'Financial Approval'
CONST_CAT_APP = 'Category Approval'

# shop assist status
CONST_SC_ASSIST_SAVE = 'SC_ASSIST_SAVE'
CONST_SC_ASSIST_SUBMIT = 'SC_ASSIST_SUBMIT'

# Scheader Status
CONST_SC_HEADER_INCOMPLETE = "PURCHASER_WORKLIST"
CONST_SC_HEADER_SAVED = 'SAVED'
CONST_SC_HEADER_AWAITING_APPROVAL = 'AWAITING_APPROVAL'
CONST_SC_HEADER_APPROVED = 'APPROVED'
CONST_SC_HEADER_REJECTED = 'REJECTED'
CONST_SC_HEADER_ORDERED = 'ORDERED'
CONST_SC_HEADER_DELETED = 'DELETED'

# PoHeader Status
CONST_PO_STATUS_ORDERED = 'ORDERED'

# System_user
CONST_SYSTEM_USER = 'MJBATCH'

# Note Types
CONST_SUPPLIER_NOTE = 'Supplier Note'
CONST_INTERNAL_NOTE = 'Internal Note'
CONST_APPROVER_NOTE = 'Approver Note'

# Notification
CONST_NOTIF_WF = 'WORKFLOW'
CONST_NOTIF_ORGMODEL = 'ORGMODEL'

# bus type
CONST_BUS_TYPE_SC = 'DOC01'  # Shopping cart
CONST_BUS_TYPE_ATTRIBUTES = 'ATTRIBUTES'  # Shopping cart

CONST_LINK_DOC_DETAIL = ['WF001', 'WF002']
CONST_LINK_CHAT = ['WF003', 'WF004']

CONST_ASSIGN = "ASSIGN"
CONST_UNASSIGN = "UNASSIGN"

# Authorization objects for shopper plus roles
CONST_AUTH_GROUP_ROLES = []

# Password related constants
CONST_NO_PSWD_POLICY = 'No Password Policy'

# Image type
CONST_CATALOG_IMAGE_TYPE = 'catalog'
CONST_UNSPSC_IMAGE_TYPE = 'unspsc'
CONST_SUPPLIER_IMAGE_TYPE = 'supplier'

# Favourite shopping cart limit
CONST_FAVOURITE_SC_LIMIT = 4

# Frequently purchased items in the company limit
CONST_POPULAR_ITEMS_LIMIT = 10

# User recently viewed items
CONST_USER_RECENTLY_VIEWED = 10

# Org Announcement active
CONST_ANNOUNCEMENT_ACTIVE = 'Active'

# Org Announcement inactive
CONST_ANNOUNCEMENT_INACTIVE = 'Inactive'

# org support
CONST_EMAIL_SUPPORT = 'EMAIL_SUPPORT'
CONST_PHONE_SUPPORT = 'PHONE_SUPPORT'

CONST_CALENDAR_ID = 'CALENDAR_ID'

CONST_CATALOG_ITEM_VARIANT = 'CATALOG_ITEM_VARIANT'
CONST_FT_ITEM_EFORM = 'FT_ITEM_EFORM'

# pricing type
# CONST_VARIANT_BASE_PRICING = 'VARIANT_BASE_PRICING'
# CONST_VARIANT_ADDITIONAL_PRICING = 'VARIANT_ADDITIONAL_PRICING'
# CONST_VARIANT_WITHOUT_PRICING = 'WITHOUT_PRICING'
# CONST_QUANTITY_BASED_DISCOUNT = 'QUANTITY'

# product info type
CONST_PRODUCT_SPECIFICATION = 'SPECIFICATIONS'

# dropdown data type
CONST_DROPDOWN_DATA_TYPE = 'DROPDOWN'

# variant type
CONST_VARIANT_WITHOUT_PRICING = 'VARIANT_WITHOUT_PRICING'
CONST_QUANTITY_BASED_DISCOUNT = 'QUANTITY_BASED_DISCOUNT'
CONST_VARIANT_BASE_PRICING = 'VARIANT_BASE_PRICING'
CONST_VARIANT_ADDITIONAL_PRICING = 'VARIANT_ADDITIONAL_PRICING'

# operator
CONST_OPERATOR_PLUS = 'PLUS'
CONST_OPERATOR_PERCENTAGE = 'PERCENTAGE'
CONST_SEARCH_COUNT = 100

# Configuration actions
CONST_ACTION_UPDATE = 'UPDATE'
CONST_ACTION_ADD = 'ADD'
CONST_ACTION_COPY = 'COPY'
CONST_ACTION_DELETE = 'DELETE'

#  PO split type
CONST_PO_SPLIT_SUPPLIER = 1
CONST_PO_SPLIT_CURRENCY = 2
CONST_PO_SPLIT_SHIP_TO_ADDRESS = 3
CONST_PO_SPLIT_PURCHASING_GROUP = 4
CONST_PO_SPLIT_CALL_OFF = 5
CONST_PO_SPLIT_LIMIT_ORDER = 6
CONST_PO_SPLIT_PURCHASE_REQUISITION = 7
CONST_PO_SPLIT_INCOTERM = 8
CONST_PO_SPLIT_PAYMENT_TERMS = 9
CONST_PO_SPLIT_PRODUCT_TYPE = 10

CONST_PO_GROUP_CURRENCY = 2
CONST_PO_GROUP_COMPANY_CODE = 3
CONST_PO_DELIVERY_DATE = 4

# PO Transmission error type
CONST_ERROR_SPLIT_CRITERIA = "PO_SPLIT_CRITERIA_ERROR"
CONST_ERROR_TRANSACTION_TYPE = "TRANSACTION_TYPE_ERROR"
CONST_VALIDATION_ERROR = 'VALIDATION_ERROR'
CONST_NOT_FOUND_ERROR = 'NOT_FOUND_ERROR'
CONST_OTHER_ERROR = 'OTHERS'
CONST_DEFAULT_LANGUAGE = 'EN'

CONST_EMAIL_STATUS = 'SENT'

# csv file list
CONST_COUNTRIES_CSV = 'Countries.CSV'
CONST_CURRENCY_CSV = 'CURRENCY.csv'
CONST_TIMEZONE_CSV = 'TIMEZONE.csv'
CONST_LANGUAGES_CSV = 'Languages.CSV'
CONST_UOM_CSV = 'Unit Of Measure.CSV'
CONST_PRODUCT_CATEGORY_CSV = 'PRODUCT CATEGORY.csv'
CONST_CLIENT_CSV = 'OrgClients.csv'
CONST_DOCUMENT_CSV = 'DocumentType.csv'
CONST_CALENDAR_CSV = 'CalenderConfig.csv'
CONST_CALENDAR_HOLIDAY_CSV = 'CalenderHolidays.csv'
CONST_ORG_NODE_TYPES_CSV = 'OrgNodeTypes.csv'
CONST_ORG_ATTRIBUTES_CSV = 'OrgAttributes.csv'
CONST_ORG_ATTRIBUTES_LEVEL_CSV = 'orgattributelevel.csv'
CONST_ORG_NODE_LEVEL_ATTRIBUTES_CSV = 'OrgModelNodetypeConfig.csv'
CONST_ACCOUNT_ASSIGNMENT_CATEGORY_CSV = 'AccountAssignmentCategory.csv'
CONST_FAVOURITE_CART_NUMBER_RANGE_CSV = 'NumberRanges.csv'
CONST_SHOPPING_CART_NUMBER_RANGE_CSV = 'NumberRanges.csv'
CONST_PURCHASE_ORDER_NUMBER_RANGE_CSV = 'NumberRanges.csv'
CONST_GOODS_VERIFICATION_NUMBER_RANGE_CSV = 'NumberRanges.csv'
CONST_FAVOURITE_TRANSACTION_TYPE_CSV = 'transaction_type.csv'
CONST_SHOPPING_CART_TRANSACTION_TYPE_CSV = 'transaction_type.csv'
CONST_PURCHASE_ORDER_TRANSACTION_TYPE_CSV = 'transaction_type.csv'
CONST_GOODS_VERIFICATION_TRANSACTION_TYPE_CSV = 'transaction_type.csv'
CONST_PO_SPLIT_TYPE_CSV = 'PoSplitType.csv'
CONST_PO_SPLIT_CRITERIA_CSV = 'PoSplitCriteria.csv'
CONST_PURCHASE_CONTROL_CSV = 'PurchaseControl.csv'
CONST_SOURCE_RULE_CSV = 'SourceRuleGeneric.csv'
CONST_SOURCE_MAPPING_CSV = 'SourceMappingSpecific.csv'
CONST_USER_ROLES_CSV = 'UserRoles.csv'
CONST_AUTHORIZATION_OBJECT = 'AuthorizationObject.csv'
CONST_AUTHORIZATION = 'Authorization.csv'
CONST_AUTHORIZATION_GROUP = 'AuthorizationGroup.csv'
CONST_FIELD_TYPE_DESC = 'FieldTypeDescription.csv'
CONST_FIELD_DESC = 'FieldDesc.csv'
CONST_MESSAGE_ID_CSV = 'MessagesId.csv'
CONST_MESSAGE_ID_DESC_CSV = 'MessagesIdDesc.csv'
CONST_SYSTEM_SETTINGS_CONFIG_CSV = 'SystemSettingsConfig.csv'
CONST_EMAIL_CONTENTS_CSV = 'emailcontents.csv'
CONST_UNSPSC_CODE_CSV = 'productcategory.csv'
CONST_PRODUCT_DETAIL_TEMPLATE_CSV = 'ProductsDetailTemplate.CSV'
CONST_PRODUCT_DETAIL_CSV = 'ProductsDetail.CSV'
CONST_PRODUCT_SPECIFICATION_TEMPLATE_CSV = 'ProductSpecification.CSV'
CONST_COFIG_UI_MESSAGE_LIST = ['JMSG001', 'JMSG002', 'JMSG003', 'JMSG004', 'JMSG005', 'JMSG009', 'JMSG113', 'JMSG029',
                               'JMSG016', 'JMSG025', 'JMSG035', 'JMSG036', 'JMSG037', 'JMSG109', 'JMSG112', 'JMSG300',
                               'JMSG017', 'JMSG054']

CONST_TIME_SHEET_UI_MESSAGE_LIST = ['JMSG111', 'JMSG039']

# system attributes
CONST_ACCOUNT_ASSIGNMENT_CATEGORY = 'ACCOUNT_ASSIGNMENT_CATEGORY'
CONST_PURCHASE_GROUPS = 'PURCHASE_GROUPS'
CONST_EDIT_ADDRESS = 'EDIT_ADDRESS'
CONST_CHANGE_SHIPPING_ADDRESS = 'CHANGE_SHIPPING_ADDRESS'
CONST_SYSTEM_ATTACHMENT_SIZE = 'ATTACHMENT_SIZE'
CONST_ATTACHMENT_EXTENSION = 'ATTACHMENT_EXTENSION'
